<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gg_extbase"
 *
 * Auto generated by Extension Builder 2014-09-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Generic Gallery Extbase',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Felix Nagel',
	'author_email' => 'info@felixnagel.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'generic_gallery' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);