# Include this route enhancer config:
# imports:
#  - { resource: "EXT:generic_gallery/Configuration/Routes/Default.yaml" }
routeEnhancers:
  GenericGalleryPi1Plugin:
    type: Extbase
    extension: GenericGallery
    defaultController: 'GalleryCollection::show'
    plugin: Pi1
    routes:
      - routePath: '/'
        _controller: 'GalleryCollection::show'
      - routePath: '/{prefix_localized_collection}/{page}'
        _controller: 'GalleryCollection::show'
        _arguments:
          'page': 'page'
      - routePath: '/{prefix_localized_item}/{ce}/{item}'
        _controller: 'GalleryItem::show'
        _arguments:
          'ce': 'contentElement'
          'item': 'item'
      - routePath: '/{prefix_localized_item}/{ce}/{file}'
        _controller: 'GalleryItem::show'
        _arguments:
          'ce': 'contentElement'
          'file': 'file'
    requirements:
      ce: '\d+'
      page: '\d+'
    aspects:
      prefix_localized_item:
        type: LocaleModifier
        default: 'image'
        localeMap:
          - locale: 'de_DE.*'
            value: 'bild'
      prefix_localized_collection:
        type: LocaleModifier
        default: 'page'
        localeMap:
          - locale: 'de_DE.*'
            value: 'seite'
      ce:
        type: PersistedPatternMapper
        tableName: 'tt_content'
        routeFieldPattern: '^(?P<uid>.+)$'
        routeFieldResult: '{uid}'
      item:
        type: PersistedPatternMapper
        # For single images
        tableName: 'tx_generic_gallery_pictures'
        routeFieldPattern: '^(?P<uid>.+)$'
        routeFieldResult: '{uid}'
      file:
        type: PersistedPatternMapper
        # For file references (multiple images and collections)
        tableName: 'sys_file'
        routeFieldPattern: '^file-(?P<uid>.+)$'
        routeFieldResult: 'file-{uid}'
      page:
        type: StaticRangeMapper
        start: '1'
        end: '99'
