services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FelixNagel\GenericGallery\:
    resource: '../Classes/*'

  # Dependency injection
  FelixNagel\GenericGallery\Service\SettingsService:
    public: true
